#!/bin/bash

if [ -z "$(ls -A /sys/class/backlight)" ]; then
  exit 1
else
  brightness=$(light | cut -d. -f1)
  text=$brightness

  if [[ brightness -gt 66 ]]; then
    class="bright"
  elif [[ brightness -gt 33 ]]; then
    class="medium"
  else
    class="dim"
  fi

  echo -e "{\"text\":\""$text"\", \"class\":\""$class"\"}"
fi
