#!/bin/bash

cachedir=~/.cache/rbn
cachefile=${0##*/}-$1

if [ ! -d $cachedir ]; then
    mkdir -p $cachedir
fi

if [ ! -f $cachedir/$cachefile ]; then
    touch $cachedir/$cachefile
fi

# Save current IFS
SAVEIFS=$IFS
# Change IFS to new line.
IFS=$'\n'

cacheage=$(($(date +%s) - $(stat -c '%Y' "$cachedir/$cachefile")))
if [ $cacheage -gt 1740 ] || [ ! -s $cachedir/$cachefile ]; then
    data=($(curl -s https://en.wttr.in/$1\?0qnT 2>&1))
    echo ${data[0]} | cut -f1 -d, > $cachedir/$cachefile
    echo ${data[1]} | sed -E 's/^.{15}//' >> $cachedir/$cachefile
    echo ${data[2]} | sed -E 's/^.{15}//' >> $cachedir/$cachefile
fi

weather=($(cat $cachedir/$cachefile))

# Restore IFSClear
IFS=$SAVEIFS

temperature=$(echo ${weather[2]} | sed -E 's/([[:digit:]])+\.\./\1 to /g')

# https://fontawesome.com/icons?s=solid&c=weather
case ${weather[1]} in
"Clear" | "Sunny")
    condition=""
    ;;
"Partly cloudy")
    condition=""
    ;;
"Cloudy")
    condition=""
    ;;
"Overcast")
    condition=""
    ;;
"Mist" | "Fog" | "Freezing fog")
    condition=""
    ;;
"Patchy rain possible" | "Patchy light drizzle" | "Light drizzle" | "Patchy light rain" | "Light rain" | "Light rain shower")
    condition=""
    ;;
"Moderate rain at times" | "Moderate rain" | "Heavy rain at times" | "Heavy rain" | "Moderate or heavy rain shower" | "Torrential rain shower")
    condition=""
    ;;
"Patchy snow possible" | "Patchy sleet possible" | "Patchy freezing drizzle possible" | "Freezing drizzle" | "Heavy freezing drizzle" | "Light freezing rain" | "Moderate or heavy freezing rain" | "Light sleet" | "Ice pellets" | "Light sleet showers" | "Moderate or heavy sleet showers")
    condition=""
    ;;
"Blowing snow" | "Moderate or heavy sleet" | "Patchy light snow" | "Light snow" | "Light snow showers")
    condition=""
    ;;
"Blizzard" | "Patchy moderate snow" | "Moderate snow" | "Patchy heavy snow" | "Heavy snow" | "Moderate or heavy snow with thunder" | "Moderate or heavy snow showers")
    condition=""
    ;;
"Thundery outbreaks possible" | "Patchy light rain with thunder" | "Moderate or heavy rain with thunder" | "Patchy light snow with thunder")
    condition=""
    ;;
*)
    condition="Error"
    ;;
esac

#echo $temp $condition

echo -e "{\"text\":\""$temperature $condition"\", \"alt\":\""${weather[0]}"\", \"tooltip\":\""${weather[0]}: $temperature ${weather[1]}"\"}"
